/*
 * Copyright 2015 Jewel of the East
 */

package FRSJoE;

import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author Deepak Kumar
 */

public class Screen1 extends javax.swing.JFrame {
    private DisplayMgr Dsmgr;
    private DataManager Dtmgr;
    private String DepartureDate;
    private String NumPassengers;
    private String StartAirport;
    private String[] Query;
    /**
     * Creates new form Screen1
     */
    public Screen1() {
        
        initComponents();
        Thread t = new Thread(){
           public void run(){
               int count = 1;
               while(true){
                   switch(count){
                       case 1:
                           picLabel1.setVisible(true);
                           picLabel2.setVisible(false);
                           picLabel3.setVisible(false);
                           try{
                              Thread.sleep(1000);
                           }catch(Exception ex){}
                           count = 2;
                           break;
                       case 2:
                           picLabel1.setVisible(false);
                           picLabel2.setVisible(true);
                           picLabel3.setVisible(false);
                           try{
                              Thread.sleep(1000);
                           }catch(Exception ex){}
                           count = 3;
                           break;
                       case 3:
                           picLabel1.setVisible(false);
                           picLabel2.setVisible(false);
                           picLabel3.setVisible(true);
                           try{
                              Thread.sleep(1000);
                           }catch(Exception ex){}
                           count = 1;
                           break;
                       default :
                   }
               }
           }
        };
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Source = new javax.swing.JComboBox();
        departDate = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NumPass = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Source1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        departDate1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        NumPass1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        picLabel1 = new javax.swing.JLabel();
        picLabel2 = new javax.swing.JLabel();
        picLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setFocusCycleRoot(true);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("LEAVING FROM:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 70, 161, 20);

        Source.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Source.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DELHI", "MUMBAI", "PUNE" }));
        jPanel1.add(Source);
        Source.setBounds(177, 69, 121, 23);

        departDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", " " }));
        jPanel1.add(departDate);
        departDate.setBounds(177, 146, 82, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("DEPARTURE DATE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 147, 161, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("NUMBER OF PASSENGERS");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 217, 161, 17);

        NumPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NumPass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        NumPass.setSelectedItem(NumPass);
        jPanel1.add(NumPass);
        NumPass.setBounds(177, 214, 44, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("GOING TO:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(428, 70, 85, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("FIND FLIGHTS");
        jPanel1.add(jButton1);
        jButton1.setBounds(535, 269, 119, 38);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FLIGHT SEARCH");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 675, 51);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SINGAPORE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(564, 72, 90, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("OCTOBER");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(339, 149, 62, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText(" DAY                                   MONTH  ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(177, 112, 224, 28);

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 34, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 922, 0);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("FLIGHT SEARCH");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 250, 675, 51);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("SOURCE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 340, 161, 20);

        Source1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Source1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DELHI", "MUMBAI", "PUNE" }));
        getContentPane().add(Source1);
        Source1.setBounds(210, 340, 121, 23);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("GOING TO:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(600, 390, 85, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("SINGAPORE");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(730, 392, 90, 17);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText(" DATE");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(80, 390, 161, 20);

        departDate1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        departDate1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        getContentPane().add(departDate1);
        departDate1.setBounds(200, 410, 40, 23);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText(" DAY         MONTH      YEAR  ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 380, 190, 28);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("OCTOBER     2015");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(250, 410, 140, 17);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("NUMBER OF PASSENGERS");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(80, 490, 171, 17);

        NumPass1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NumPass1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        NumPass1.setSelectedItem(NumPass);
        getContentPane().add(NumPass1);
        NumPass1.setBounds(300, 490, 42, 23);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("FIND FLIGHTS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(810, 540, 160, 38);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRSJoE/background.jpg"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 230, 1024, 380);

        picLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRSJoE/pic1.jpg"))); // NOI18N
        getContentPane().add(picLabel1);
        picLabel1.setBounds(0, -10, 1024, 240);

        picLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRSJoE/pic2.jpg"))); // NOI18N
        picLabel2.setText("jLabel20");
        getContentPane().add(picLabel2);
        picLabel2.setBounds(0, 0, 1030, 220);

        picLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRSJoE/pic3.jpg"))); // NOI18N
        picLabel3.setText("jLabel18");
        getContentPane().add(picLabel3);
        picLabel3.setBounds(0, 0, 1030, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents
             
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NumPassengers = NumPass1.getSelectedItem().toString();
        DepartureDate = departDate1.getSelectedItem().toString();
        StartAirport = Source1.getSelectedItem().toString();
        Query = new String[3];
        Query[2]=this.NumPassengers;
        Query[1]=this.DepartureDate;
        Query[0]=this.StartAirport;
        Dsmgr.setDateScreen4(departDate1.getSelectedItem().toString());
        Dsmgr.setNumPassScreen3(NumPass1.getSelectedItem().toString());
        Dsmgr.showScreen2(Query);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param MgrObj
     */
    public void invokeScreen1(DisplayMgr MgrObj){
        Dsmgr = MgrObj;
        NumPassengers = NumPass1.getSelectedItem().toString();
        DepartureDate = departDate1.getSelectedItem().toString();
        this.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox NumPass;
    private javax.swing.JComboBox NumPass1;
    private javax.swing.JComboBox Source;
    private javax.swing.JComboBox Source1;
    private javax.swing.JComboBox departDate;
    private javax.swing.JComboBox departDate1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel picLabel1;
    private javax.swing.JLabel picLabel2;
    private javax.swing.JLabel picLabel3;
    // End of variables declaration//GEN-END:variables
}
