/*
 * Copyright 2015 Jewel of the East
 */

package FRSJoE;

import javax.swing.JOptionPane;

/**
 *
 * @author Deepak Kumar
 */
public class Screen4 extends javax.swing.JFrame {
    private DisplayMgr dSMgr;
    /**
     * Creates new form Screen4
     */
    Screen2 s;
    public Screen4(Screen2 s) {
        this.s = s;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        HeadingLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Text5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("CONFIRM & EXIT!");
        jButton2.setPreferredSize(new java.awt.Dimension(160, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 560, 160, 35);

        HeadingLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        HeadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadingLabel.setText("TRAVEL ITERNARY");
        getContentPane().add(HeadingLabel);
        HeadingLabel.setBounds(230, 20, 577, 56);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Departure Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 220, 160, 24);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Flight Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 190, 160, 24);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Booking Reference no.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 160, 160, 24);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Passenger Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 130, 130, 24);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("CONFIRM & BOOK AGAIN!");
        jButton1.setPreferredSize(new java.awt.Dimension(160, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 560, 220, 35);

        Text1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Text1);
        Text1.setBounds(290, 130, 210, 24);

        Text2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Text2);
        Text2.setBounds(290, 160, 210, 24);

        Text3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Text3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Text3);
        Text3.setBounds(290, 190, 210, 24);

        Text4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Text4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Text4);
        Text4.setBounds(290, 220, 210, 24);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Number of Passengers");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 250, 160, 26);

        Text5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Text5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Text5);
        Text5.setBounds(290, 250, 210, 25);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 60, 900, 530);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText(" FLIGHT DETAILS : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 310, 160, 30);

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            s.data,
            new String [] {
                "Origin", "Departure", "FlightNumber(Spicejet)", "Arrival to via","via","Departure From via","Flight Number(SilkAir)","Arrival"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(52, 362, 940, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRSJoE/background.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1020, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dSMgr.showscreen1();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for reserving Flights with us!\n Please visit again!");
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void invokeScreen4(DisplayMgr MgrObj,Booking bookerfinal,String depart){
    dSMgr = MgrObj;
    Text1.setText(bookerfinal.getpassName());
    Text2.setText(bookerfinal.getrefNum());
    Text3.setText(bookerfinal.getFltNum());
    Text4.setText(depart+" OCT 2015");
    Text5.setText(bookerfinal.getNumPass());
    this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
