 /*
 * Copyright 2015 Jewel of the East
 */

package FRSJoE;

import javax.swing.JOptionPane;

/**
 *
 * @author Deepak Kumar
 */
public class Screen3 extends javax.swing.JFrame {
    private DisplayMgr DSMgr;
    /**
     * Creates new form Screen3
     */
    private Flight SlFlight;
    private String pass,dep;
    private int flrowindex;
    Screen2 s;
    public Screen3(Screen2 s) {
        this.s = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        FName = new javax.swing.JLabel();
        LName = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        Text2 = new javax.swing.JTextField();
        Text3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LName1 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 650));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 600));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PASSENGER DETAILS");
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 100));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 150, 598, 43);

        Title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Title.setText("Email");
        jPanel1.add(Title);
        Title.setBounds(70, 370, 120, 33);

        FName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        FName.setText("First Name");
        jPanel1.add(FName);
        FName.setBounds(90, 230, 103, 35);

        LName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LName.setText("Last Name");
        jPanel1.add(LName);
        LName.setBounds(80, 300, 114, 27);

        Text1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Text1);
        Text1.setBounds(440, 230, 365, 34);

        Text2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Text2);
        Text2.setBounds(440, 300, 365, 35);

        Text3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Text3);
        Text3.setBounds(440, 370, 365, 34);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("BOOK");
        jButton1.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(820, 530, 110, 39);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setPreferredSize(new java.awt.Dimension(60, 60));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 530, 110, 39);

        LName1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LName1.setText("No. of Passengers");
        jPanel1.add(LName1);
        LName1.setBounds(110, 430, 140, 42);

        Text4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Text4);
        Text4.setBounds(440, 430, 365, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FRSJoE/background.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 990, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DSMgr.showscreen1();
    }//GEN-LAST:event_jButton2ActionPerformed

                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Text1.getText().equalsIgnoreCase("") || Text2.getText().equalsIgnoreCase("") || Text3.getText().equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(rootPane, "All fields are MANDATORY!");
        else{
        DSMgr.showScreen4(Text1.getText()+" "+Text2.getText(),Integer.parseInt(pass),dep,SlFlight,flrowindex,s,Text3.getText());
        this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void invokeScreen3(DisplayMgr MgrObj, Flight selectFlight,String Numpass,String depart,int rowindex){
        DSMgr = MgrObj;
        SlFlight = selectFlight;
        dep = depart;
        pass = Numpass;
        Text4.setText(pass);
        flrowindex=rowindex;
        Text1.setText("");
        Text2.setText("");
        Text3.setText("");
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FName;
    private javax.swing.JLabel LName;
    private javax.swing.JLabel LName1;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
